//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGDRL.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGRenLuyen
    {
        public int NamHoc { get; set; }
        public string MaHK { get; set; }
        public string MSSV { get; set; }
        public int MaTC { get; set; }
        public int MaLC { get; set; }
        public Nullable<int> DiemSVDG { get; set; }
        public Nullable<int> DiemLT { get; set; }
        public Nullable<int> DiemCVHT { get; set; }
    }
}
