//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGDRL.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string MSSV { get; set; }
        public int NamHoc { get; set; }
        public string MaHK { get; set; }
        public Nullable<int> TongDiemSV { get; set; }
        public Nullable<int> TongDiemLT { get; set; }
        public Nullable<int> TongDiemCVHT { get; set; }
        public string XepLoai { get; set; }
    }
}
