//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGDRL.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuaChonChiTiet
    {
        public int MaLC { get; set; }
        public Nullable<int> MaCT { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DiemMin { get; set; }
        public Nullable<int> DiemMax { get; set; }
    }
}
