//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGDRL.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDungChiTiet
    {
        public int MaCT { get; set; }
        public Nullable<int> MaTC { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DiemCTMax { get; set; }
    }
}
